#!/bin/bash

#
## Check if Postgresql is in place
#
if [ -z $OPENSHIFT_POSTGRESQL_DB_HOST ]
then
    echo 1>&2
    echo "Could not find postgresql database.  Please run:" 1>&2
    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c postgresql-9.2" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
    exit 5
fi

#
## Install LiquidFeedback Core 2.2.1
#
cd $OPENSHIFT_REPO_DIR/lqfb/liquid_feedback_core-v2.2.1
make
mkdir $OPENSHIFT_REPO_DIR/liquid_feedback_core
cp core.sql lf_update $OPENSHIFT_REPO_DIR/liquid_feedback_core/

#
## Install WebMCP 1.2.5
#
export OPENSHIFT_REPO_DIR_SAFE=$(echo $OPENSHIFT_REPO_DIR | sed -r 's/\//\\\//g')
cd $OPENSHIFT_REPO_DIR/lqfb/webmcp-v1.2.5
sed -i 's/CFLAGS .*/CFLAGS = -O2 -D_GNU_SOURCE -fPIC -Wall -I \/usr\/include -I \/usr\/local\/include -I '$OPENSHIFT_REPO_DIR_SAFE'lqfb\/lua-5.1.4\/src/' Makefile.options
sed -i "s/CFLAGS_PGSQL .*/CFLAGS_PGSQL = -I \/usr\/include\/pgsql -I \/usr\/include\/pgsql\/server -I \/usr\/local\/include\/pgsql -I \/usr\/local\/include\/pgsql\/server\//" Makefile.options
make
mkdir $OPENSHIFT_REPO_DIR/webmcp
cp -RL framework/* $OPENSHIFT_REPO_DIR/webmcp/