#!/bin/bash

#
## Check if Postgresql is in place
#
if [ -z $OPENSHIFT_POSTGRESQL_DB_HOST ]
then
    echo 1>&2
    echo "Could not find postgresql database.  Please run:" 1>&2
    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c postgresql-9.2" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
    exit 5
fi

#
## Install LiquidFeedback Core 2.2.1
#
cd $OPENSHIFT_REPO_DIR/lqfb/liquid_feedback_core-v2.2.1
make
mkdir $OPENSHIFT_REPO_DIR/liquid_feedback_core
cp core.sql lf_update $OPENSHIFT_REPO_DIR/liquid_feedback_core/

#
## Install WebMCP 1.2.5
#
cd $OPENSHIFT_REPO_DIR/lqfb/webmcp-v1.2.5
#vi Makefile.options  # append  -I /usr/include/lua5.1  at end of CFLAGS line
make
mkdir $OPENSHIFT_REPO_DIR/webmcp
cp -RL framework/* $OPENSHIFT_REPO_DIR/webmcp/